// ═══════════════════════════════════════════════════════════════════
// QUOTES VIEW MODULES — Types & Components
// ═══════════════════════════════════════════════════════════════════

import React from 'react'
import { motion } from 'framer-motion'
import type { LocalSupplier, SupplierDocument, ViewingDocument } from '../../types'
import { formatFileSize } from '../../types'
import { ID } from '../../../types'

export interface QuotesViewProps { suppliers: LocalSupplier[]; quotesFileInputRef: React.RefObject<HTMLInputElement>; quotesUploadingFor: ID | null; setQuotesUploadingFor: (id: ID | null) => void; updateSupplier: (id: ID, data: Partial<LocalSupplier>) => void; setViewingDocument: (v: ViewingDocument | null) => void; downloadDocument: (doc: SupplierDocument) => void; showToast: (message: string, type?: string) => void; setActiveView: (v: 'suppliers' | 'quotes') => void }

export const EmptyQuotes: React.FC<{ setActiveView: (v: 'suppliers' | 'quotes') => void }> = ({ setActiveView }) => (
    <div className="bg-white dark:bg-zinc-950 rounded-[2.5rem] p-12 border border-zinc-200/50 dark:border-white/10 text-center shadow-lg"><div className="w-20 h-20 bg-gradient-to-br from-amber-100 to-orange-100 dark:from-amber-500/10 dark:to-orange-500/10 rounded-3xl flex items-center justify-center mx-auto mb-6"><svg className="w-10 h-10 text-amber-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg></div><h3 className="text-xl font-bold text-zinc-900 dark:text-white mb-2">Nenhuma cotação</h3><p className="text-zinc-500 dark:text-zinc-400 mb-6">Adicione cotações aos seus fornecedores</p><button onClick={() => setActiveView('suppliers')} className="px-6 py-3 bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 rounded-xl font-bold text-sm hover:scale-105 active:scale-95 transition-all">Ver Fornecedores</button></div>
)

interface SupplierQuoteCardProps { supplier: LocalSupplier; quotesFileInputRef: React.RefObject<HTMLInputElement>; setQuotesUploadingFor: (id: ID | null) => void; updateSupplier: (id: ID, data: Partial<LocalSupplier>) => void; setViewingDocument: (v: ViewingDocument | null) => void; downloadDocument: (doc: SupplierDocument) => void; showToast: (message: string, type?: string) => void }

export const SupplierQuoteCard: React.FC<SupplierQuoteCardProps> = ({ supplier, quotesFileInputRef, setQuotesUploadingFor, updateSupplier, setViewingDocument, downloadDocument, showToast }) => {
    const quotes = (supplier.documents || []).filter(d => d.category === 'cotacao')
    return (
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} whileHover={{ y: -4 }} className="bg-white dark:bg-zinc-950 rounded-[2rem] p-6 border border-zinc-200/50 dark:border-white/10 shadow-lg hover:shadow-2xl transition-all">
            <div className="flex items-start gap-4 mb-5"><div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center text-white text-xl font-bold shadow-lg shadow-amber-500/25">{supplier.name?.charAt(0)?.toUpperCase() || '?'}</div><div className="flex-1 min-w-0"><h3 className="text-lg font-bold text-zinc-900 dark:text-white truncate">{supplier.name}</h3>{supplier.company && <p className="text-sm text-zinc-500 dark:text-zinc-400 truncate">{supplier.company}</p>}</div><button onClick={() => { setQuotesUploadingFor(supplier.id); quotesFileInputRef.current?.click() }} className="w-10 h-10 rounded-xl bg-amber-50 dark:bg-amber-500/10 flex items-center justify-center text-amber-500 hover:bg-amber-100 dark:hover:bg-amber-500/20 transition-colors touch-manipulation"><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}><path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" /></svg></button></div>
            <div className="flex items-center gap-2 px-3 py-2 bg-amber-50 dark:bg-amber-500/10 rounded-xl border border-amber-100 dark:border-amber-500/20 mb-4"><svg className="w-4 h-4 text-amber-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg><span className="text-xs font-bold text-amber-600 dark:text-amber-400">{quotes.length} {quotes.length === 1 ? 'cotação' : 'cotações'}</span></div>
            <div className="space-y-2">{quotes.map(doc => (
                <button type="button" key={doc.id} className="w-full flex items-center gap-3 p-3 bg-zinc-50 dark:bg-zinc-900/50 rounded-xl group hover:bg-zinc-100 dark:hover:bg-zinc-800/50 transition-colors cursor-pointer text-left" onClick={(e) => setViewingDocument({ doc, originRect: e.currentTarget.getBoundingClientRect() })}>
                    {doc.type.startsWith('image/') ? <div className="w-10 h-10 rounded-lg bg-cover bg-center shrink-0 shadow-sm ring-1 ring-black/5" style={{ backgroundImage: `url(${doc.dataUrl})` }} /> : <div className={`w-10 h-10 rounded-lg flex items-center justify-center shrink-0 ${doc.type === 'application/pdf' ? 'bg-red-100 dark:bg-red-500/20' : doc.type.includes('spreadsheet') || doc.type.includes('excel') ? 'bg-emerald-100 dark:bg-emerald-500/20' : 'bg-blue-100 dark:bg-blue-500/20'}`}><span className="text-lg">{doc.type === 'application/pdf' ? '📕' : doc.type.includes('spreadsheet') || doc.type.includes('excel') ? '📊' : '📝'}</span></div>}
                    <div className="flex-1 min-w-0"><p className="text-sm font-medium text-zinc-900 dark:text-white truncate">{doc.name}</p><p className="text-xs text-zinc-500 dark:text-zinc-400">{formatFileSize(doc.size)} · {new Date(doc.uploadedAt).toLocaleDateString('pt-BR')}</p></div>
                    <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity"><button onClick={(e) => { e.stopPropagation(); downloadDocument(doc) }} className="w-8 h-8 flex items-center justify-center rounded-lg text-blue-500 hover:bg-blue-50 dark:hover:bg-blue-500/10 transition-colors touch-manipulation"><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg></button><button onClick={(e) => { e.stopPropagation(); updateSupplier(supplier.id, { documents: supplier.documents?.filter(d => d.id !== doc.id) || [] }); showToast('Cotação removida') }} className="w-8 h-8 flex items-center justify-center rounded-lg text-red-500 hover:bg-red-50 dark:hover:bg-red-500/10 transition-colors touch-manipulation"><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg></button></div>
                </button>
            ))}</div>
        </motion.div>
    )
}
