// ═══════════════════════════════════════════════════════════════════
// INGREDIENT LIST MOBILE MODULES — Types & Components
// ═══════════════════════════════════════════════════════════════════

import React from 'react'
import type { ID } from '../../../types'
import type { PizzaIngredient } from '../../types'

export interface IngredientListMobileProps { ingredients: PizzaIngredient[]; editingId: ID | null; setEditingId: (id: ID | null) => void; handleUpdateIngredient: (id: ID, field: string, value: string | number) => void; handleDeleteIngredient: (id: ID) => void; getItemCost: (ing: PizzaIngredient) => number; formatCurrency: (v: number) => string; totalCost: number }

interface CardProps { ing: PizzaIngredient; setEditingId: (id: ID | null) => void; handleUpdateIngredient: (id: ID, field: string, value: string | number) => void; handleDeleteIngredient: (id: ID) => void; getItemCost: (ing: PizzaIngredient) => number; formatCurrency: (v: number) => string }

export const MobileEditCard: React.FC<CardProps> = ({ ing, setEditingId, handleUpdateIngredient, handleDeleteIngredient }) => (
    <div className="space-y-4">
        <div className="flex items-center justify-between mb-2"><div className="flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-indigo-500 shadow-[0_0_8px_rgba(99,102,241,0.5)]"></div><span className="text-[10px] font-bold text-zinc-400 dark:text-zinc-500 uppercase tracking-[0.2em]">Editando</span></div><div className="flex gap-2"><button onClick={() => setEditingId(null)} className="p-2 rounded-xl text-emerald-600 dark:text-emerald-400 bg-emerald-50/50 dark:bg-emerald-500/10 hover:bg-emerald-100 dark:hover:bg-emerald-500/20 transition-all active:scale-95"><svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" /></svg></button><button onClick={() => handleDeleteIngredient(ing.id)} className="p-2 rounded-xl text-red-500 bg-red-50/50 dark:bg-red-500/10 hover:bg-red-100 dark:hover:bg-red-500/20 transition-all active:scale-95"><svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg></button></div></div>
        <div><label htmlFor={`ing-name-${ing.id}`} className="block text-[9px] font-bold text-zinc-400/80 dark:text-zinc-500 uppercase tracking-[0.2em] mb-1.5 ml-1">Nome</label><input id={`ing-name-${ing.id}`} type="text" className="w-full px-4 py-3 rounded-xl bg-zinc-50/50 dark:bg-black/20 border border-zinc-100/80 dark:border-white/5 text-zinc-700 dark:text-zinc-200 font-medium focus:outline-none focus:bg-white dark:focus:bg-black/40 focus:ring-1 focus:ring-indigo-500/30 transition-all text-sm placeholder:text-zinc-300" value={ing.name} onChange={e => handleUpdateIngredient(ing.id, 'name', e.target.value)} onBlur={() => { if (!ing.name.trim() && (!ing.quantity || ing.quantity === 0)) handleDeleteIngredient(ing.id) }} /></div>
        <div className="grid grid-cols-2 gap-3">
            <div><label htmlFor={`ing-qty-${ing.id}`} className="block text-[9px] font-bold text-zinc-400/80 dark:text-zinc-500 uppercase tracking-[0.2em] mb-1.5 ml-1">Qtd</label><input id={`ing-qty-${ing.id}`} type="number" step="any" inputMode="decimal" className="w-full px-4 py-3 rounded-xl bg-zinc-50/50 dark:bg-black/20 border border-zinc-100/80 dark:border-white/5 text-zinc-900 dark:text-white font-semibold text-lg text-right focus:outline-none focus:bg-white dark:focus:bg-black/40 focus:ring-1 focus:ring-indigo-500/30 transition-all" value={ing.quantity} onChange={e => handleUpdateIngredient(ing.id, 'quantity', e.target.value)} onBlur={() => { if (!ing.name.trim() && (!ing.quantity || ing.quantity === 0)) handleDeleteIngredient(ing.id) }} /></div>
            <div><label htmlFor={`ing-unit-${ing.id}`} className="block text-[9px] font-bold text-zinc-400/80 dark:text-zinc-500 uppercase tracking-[0.2em] mb-1.5 ml-1">Unidade</label><div className="relative"><select id={`ing-unit-${ing.id}`} className="w-full px-4 py-3 rounded-xl bg-zinc-50/50 dark:bg-black/20 border border-zinc-100/80 dark:border-white/5 text-zinc-600 dark:text-zinc-300 font-semibold text-center appearance-none focus:outline-none focus:bg-white dark:focus:bg-black/40 focus:ring-1 focus:ring-indigo-500/30 transition-all text-sm" value={ing.unit} onChange={e => handleUpdateIngredient(ing.id, 'unit', e.target.value)}><option value="g">g</option><option value="kg">kg</option><option value="ml">ml</option><option value="L">L</option><option value="un">un</option></select><div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none opacity-40"><svg xmlns="http://www.w3.org/2000/svg" className="h-3 w-3" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" /></svg></div></div></div>
        </div>
        <div><label htmlFor={`ing-price-${ing.id}`} className="block text-[9px] font-bold text-zinc-400/80 dark:text-zinc-500 uppercase tracking-[0.2em] mb-1.5 ml-1">Preço/Unidade</label><input id={`ing-price-${ing.id}`} type="number" step="1" inputMode="numeric" className="w-full px-4 py-3 rounded-xl bg-zinc-50/50 dark:bg-black/20 border border-zinc-100/80 dark:border-white/5 text-zinc-900 dark:text-white font-semibold text-lg text-right focus:outline-none focus:bg-white dark:focus:bg-black/40 focus:ring-1 focus:ring-indigo-500/30 transition-all" value={ing.pricePerUnit} onChange={e => handleUpdateIngredient(ing.id, 'pricePerUnit', e.target.value)} /></div>
    </div>
)

export const MobileViewCard: React.FC<CardProps> = ({ ing, setEditingId, getItemCost, formatCurrency }) => (
    <button type="button" onClick={() => setEditingId(ing.id)} className="group cursor-pointer w-full text-left bg-transparent border-none p-0">
        <div className="flex items-start justify-between mb-3">
            <div className="flex-1"><h4 className="font-semibold text-zinc-800 dark:text-zinc-100 text-[15px] mb-1 tracking-tight group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors">{ing.name}</h4><div className="flex items-center gap-2"><span className="inline-flex items-center px-2 py-0.5 rounded-md bg-zinc-50 dark:bg-white/5 border border-zinc-100/80 dark:border-white/5 text-[10px] font-bold text-zinc-500 dark:text-zinc-400 tabular-nums uppercase tracking-wide">{ing.quantity} {ing.unit}</span><span className="text-[10px] text-zinc-400/80 font-medium">@ {Math.round(Number(ing.pricePerUnit) || 0)}/{ing.unit}</span></div></div>
            <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity"><span className="p-2 rounded-xl text-zinc-400 hover:text-indigo-500 hover:bg-indigo-50 dark:hover:bg-indigo-500/10 transition-all"><svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" /></svg></span></div>
        </div>
        <div className="flex items-center justify-between pt-3 border-t border-dashed border-zinc-100/80 dark:border-white/5"><span className="text-[9px] font-bold text-zinc-300 dark:text-zinc-600 uppercase tracking-[0.25em]">Custo</span><span className="text-lg font-bold text-zinc-800 dark:text-zinc-200 tabular-nums tracking-tight">{formatCurrency(getItemCost(ing))}</span></div>
    </button>
)
