/**
 * MOCK DATA - Padoca Pizza Static Prototype
 * Centralized mock data for visual shell mode
 * 
 * All data is static and will not persist between sessions.
 * This is intentional for the prototype demonstration.
 */

// ═══════════════════════════════════════════════════════════════
// INVENTORY MOCK DATA
// ═══════════════════════════════════════════════════════════════

export const MOCK_INVENTORY = [
    {
        id: 1,
        name: 'Farinha de Trigo Tipo 00',
        category: 'Ingredientes',
        subcategory: 'Farináceos',
        unit: 'kg',
        packageQuantity: 25,
        packageCount: 4,
        minStock: 50,
        pricePerUnit: 89.90,
        supplier: 'Moinho Globo',
        supplierId: 1,
        notes: 'Farinha italiana premium para pizza napoletana',
        expiryDate: '2026-03-15T00:00:00Z',
        createdAt: '2025-12-15T10:00:00Z',
        updatedAt: '2025-12-28T14:30:00Z'
    },
    {
        id: 2,
        name: 'Molho de Tomate San Marzano',
        category: 'Ingredientes',
        subcategory: 'Vegetais',
        unit: 'kg',
        packageQuantity: 2.5,
        packageCount: 4,
        minStock: 15,
        pricePerUnit: 42.50,
        supplier: 'Importadora Italia',
        supplierId: 2,
        notes: 'DOP certificado - ESTOQUE CRÍTICO',
        expiryDate: '2026-01-08T00:00:00Z',
        createdAt: '2025-12-10T09:00:00Z',
        updatedAt: '2025-12-27T11:00:00Z'
    },
    {
        id: 3,
        name: 'Mussarela di Bufala',
        category: 'Ingredientes',
        subcategory: 'Laticínios',
        unit: 'kg',
        packageQuantity: 1,
        packageCount: 5,
        minStock: 5,
        pricePerUnit: 125.00,
        supplier: 'Laticínios Premium',
        supplierId: 3,
        notes: 'Produção artesanal - ESTOQUE BAIXO',
        expiryDate: '2026-01-06T00:00:00Z',
        createdAt: '2025-12-18T08:00:00Z',
        updatedAt: '2025-12-30T16:00:00Z'
    },
    {
        id: 4,
        name: 'Azeite Extra Virgem',
        category: 'Ingredientes',
        subcategory: 'Temperos',
        unit: 'L',
        packageQuantity: 5,
        packageCount: 3,
        minStock: 10,
        pricePerUnit: 189.00,
        supplier: 'Importadora Italia',
        supplierId: 2,
        notes: 'Primeira prensagem a frio',
        createdAt: '2025-12-05T14:00:00Z',
        updatedAt: '2025-12-25T10:00:00Z'
    },
    {
        id: 5,
        name: 'Pepperoni Artesanal',
        category: 'Ingredientes',
        subcategory: 'Embutidos',
        unit: 'kg',
        packageQuantity: 2,
        packageCount: 6,
        minStock: 8,
        pricePerUnit: 78.00,
        supplier: 'Embutidos Gourmet',
        supplierId: 4,
        notes: 'Cura natural 60 dias',
        createdAt: '2025-12-12T11:00:00Z',
        updatedAt: '2025-12-29T09:00:00Z'
    },
    {
        id: 6,
        name: 'Manjericão Fresco',
        category: 'Ingredientes',
        subcategory: 'Vegetais',
        unit: 'un',
        packageQuantity: 1,
        packageCount: 24,
        minStock: 12,
        pricePerUnit: 8.50,
        supplier: 'Horta Orgânica',
        supplierId: 5,
        notes: 'Orgânico certificado',
        expiryDate: '2026-01-04T00:00:00Z',
        createdAt: '2025-12-20T07:00:00Z',
        updatedAt: '2025-12-31T08:00:00Z'
    },
    {
        id: 7,
        name: 'Parmesão Reggiano 24 meses',
        category: 'Ingredientes',
        subcategory: 'Laticínios',
        unit: 'kg',
        packageQuantity: 1,
        packageCount: 3,
        minStock: 2,
        pricePerUnit: 285.00,
        supplier: 'Importadora Italia',
        supplierId: 2,
        notes: 'DOP certificado, maturação 24 meses',
        createdAt: '2025-12-08T13:00:00Z',
        updatedAt: '2025-12-26T15:00:00Z'
    },
    {
        id: 8,
        name: 'Fermento Biológico Seco',
        category: 'Ingredientes',
        subcategory: 'Farináceos',
        unit: 'g',
        packageQuantity: 500,
        packageCount: 1,
        minStock: 1000,
        pricePerUnit: 32.00,
        supplier: 'Moinho Globo',
        supplierId: 1,
        notes: 'Instantâneo - ESTOQUE CRÍTICO',
        createdAt: '2025-12-14T10:00:00Z',
        updatedAt: '2025-12-28T12:00:00Z'
    },
    {
        id: 9,
        name: 'Sal Marinho',
        category: 'Ingredientes',
        subcategory: 'Temperos',
        unit: 'kg',
        packageQuantity: 1,
        packageCount: 10,
        minStock: 5,
        pricePerUnit: 12.00,
        supplier: 'Distribuidora Central',
        supplierId: 6,
        notes: 'Moído fino',
        createdAt: '2025-12-01T09:00:00Z',
        updatedAt: '2025-12-20T14:00:00Z'
    },
    {
        id: 10,
        name: 'Presunto de Parma',
        category: 'Ingredientes',
        subcategory: 'Embutidos',
        unit: 'kg',
        packageQuantity: 0.5,
        packageCount: 8,
        minStock: 2,
        pricePerUnit: 145.00,
        supplier: 'Importadora Italia',
        supplierId: 2,
        notes: 'DOP, maturação 18 meses',
        createdAt: '2025-12-11T11:00:00Z',
        updatedAt: '2025-12-29T10:00:00Z'
    },
    {
        id: 11,
        name: 'Cogumelos Portobello',
        category: 'Ingredientes',
        subcategory: 'Vegetais',
        unit: 'kg',
        packageQuantity: 0.5,
        packageCount: 6,
        minStock: 2,
        pricePerUnit: 38.00,
        supplier: 'Horta Orgânica',
        supplierId: 5,
        notes: 'Frescos, colheita diária',
        expiryDate: '2026-01-10T00:00:00Z',
        createdAt: '2025-12-19T08:00:00Z',
        updatedAt: '2025-12-31T07:00:00Z'
    },
    {
        id: 12,
        name: 'Detergente Neutro',
        category: 'Ingredientes',
        subcategory: 'Produtos de Limpeza',
        unit: 'L',
        packageQuantity: 5,
        packageCount: 4,
        minStock: 10,
        pricePerUnit: 28.00,
        supplier: 'Distribuidora Central',
        supplierId: 6,
        notes: 'Concentrado',
        createdAt: '2025-12-03T10:00:00Z',
        updatedAt: '2025-12-22T11:00:00Z'
    },
    {
        id: 13,
        name: 'Gorgonzola',
        category: 'Ingredientes',
        subcategory: 'Laticínios',
        unit: 'kg',
        packageQuantity: 1,
        packageCount: 4,
        minStock: 2,
        pricePerUnit: 95.00,
        supplier: 'Laticínios Premium',
        supplierId: 3,
        notes: 'Dolce',
        createdAt: '2025-12-16T12:00:00Z',
        updatedAt: '2025-12-30T09:00:00Z'
    },
    {
        id: 14,
        name: 'Cebola Roxa',
        category: 'Ingredientes',
        subcategory: 'Vegetais',
        unit: 'kg',
        packageQuantity: 5,
        packageCount: 2,
        minStock: 5,
        pricePerUnit: 18.00,
        supplier: 'Horta Orgânica',
        supplierId: 5,
        notes: 'Orgânica',
        createdAt: '2025-12-21T09:00:00Z',
        updatedAt: '2025-12-31T10:00:00Z'
    },
    {
        id: 15,
        name: 'Calabresa Artesanal',
        category: 'Ingredientes',
        subcategory: 'Embutidos',
        unit: 'kg',
        packageQuantity: 2,
        packageCount: 5,
        minStock: 6,
        pricePerUnit: 52.00,
        supplier: 'Embutidos Gourmet',
        supplierId: 4,
        notes: 'Defumada naturalmente',
        createdAt: '2025-12-13T14:00:00Z',
        updatedAt: '2025-12-28T16:00:00Z'
    },
    {
        id: 16,
        name: 'Orégano Desidratado',
        category: 'Ingredientes',
        subcategory: 'Temperos',
        unit: 'g',
        packageQuantity: 100,
        packageCount: 3,
        minStock: 0,
        maxStock: 0,
        pricePerUnit: 15.00,
        supplier: 'Horta Orgânica',
        supplierId: 5,
        notes: 'Sem limite definido',
        createdAt: '2025-12-25T10:00:00Z',
        updatedAt: '2025-12-31T12:00:00Z'
    }
]

// ═══════════════════════════════════════════════════════════════
// SUPPLIERS MOCK DATA
// ═══════════════════════════════════════════════════════════════

export const MOCK_SUPPLIERS = [
    {
        id: 1,
        name: 'Moinho Globo',
        category: 'Farinhas',
        phone: '+1 (403) 555-0101',
        email: 'vendas@moinhoglobo.com',
        whatsapp: '+14035550101',
        address: '123 Industrial Ave, Calgary, AB T2P 1A1',
        website: 'https://moinhoglobo.com',
        notes: 'Entrega às terças e quintas. Pedido mínimo 100kg.',
        contactPerson: 'Roberto Silva',
        paymentTerms: 'Net 30',
        linkedItems: [1, 8],
        documents: [],
        createdAt: '2025-11-01T10:00:00Z',
        updatedAt: '2025-12-28T14:00:00Z'
    },
    {
        id: 2,
        name: 'Importadora Italia',
        category: 'Importados',
        phone: '+1 (403) 555-0202',
        email: 'orders@importadoraitalia.ca',
        whatsapp: '+14035550202',
        address: '456 Gourmet Lane, Calgary, AB T2R 2B2',
        website: 'https://importadoraitalia.ca',
        notes: 'Produtos DOP autênticos. Prazo de entrega 5-7 dias.',
        contactPerson: 'Maria Rossi',
        paymentTerms: 'Net 15',
        linkedItems: [2, 4, 7, 10],
        documents: [],
        createdAt: '2025-10-15T09:00:00Z',
        updatedAt: '2025-12-27T11:00:00Z'
    },
    {
        id: 3,
        name: 'Laticínios Premium',
        category: 'Laticínios',
        phone: '+1 (403) 555-0303',
        email: 'pedidos@laticinios.premium.ca',
        whatsapp: '+14035550303',
        address: '789 Dairy Road, Calgary, AB T2S 3C3',
        website: '',
        notes: 'Produção artesanal. Entregas diárias disponíveis.',
        contactPerson: 'João Monteiro',
        paymentTerms: 'COD',
        linkedItems: [3, 13],
        documents: [],
        createdAt: '2025-09-20T08:00:00Z',
        updatedAt: '2025-12-30T16:00:00Z'
    },
    {
        id: 4,
        name: 'Embutidos Gourmet',
        category: 'Carnes',
        phone: '+1 (403) 555-0404',
        email: 'vendas@embutidosgourmet.ca',
        whatsapp: '+14035550404',
        address: '321 Meat Market St, Calgary, AB T2T 4D4',
        website: 'https://embutidosgourmet.ca',
        notes: 'Cura artesanal. Certificação orgânica disponível.',
        contactPerson: 'Carlos Ferreira',
        paymentTerms: 'Net 7',
        linkedItems: [5, 15],
        documents: [],
        createdAt: '2025-11-10T11:00:00Z',
        updatedAt: '2025-12-29T09:00:00Z'
    },
    {
        id: 5,
        name: 'Horta Orgânica',
        category: 'Vegetais',
        phone: '+1 (403) 555-0505',
        email: 'contato@hortaorganica.ca',
        whatsapp: '+14035550505',
        address: '654 Farm Road, Okotoks, AB T1S 5E5',
        website: 'https://hortaorganica.ca',
        notes: 'Colheita diária. 100% orgânico certificado.',
        contactPerson: 'Ana Paula',
        paymentTerms: 'COD',
        linkedItems: [6, 11, 14],
        documents: [],
        createdAt: '2025-08-01T07:00:00Z',
        updatedAt: '2025-12-31T08:00:00Z'
    },
    {
        id: 6,
        name: 'Distribuidora Central',
        category: 'Diversos',
        phone: '+1 (403) 555-0606',
        email: 'vendas@distcentral.ca',
        whatsapp: '+14035550606',
        address: '987 Distribution Way, Calgary, AB T2U 6F6',
        website: 'https://distcentral.ca',
        notes: 'Entrega rápida. Amplo catálogo.',
        contactPerson: 'Pedro Santos',
        paymentTerms: 'Net 30',
        linkedItems: [9, 12],
        documents: [],
        createdAt: '2025-07-15T10:00:00Z',
        updatedAt: '2025-12-22T11:00:00Z'
    }
]

// ═══════════════════════════════════════════════════════════════
// RECIPES MOCK DATA
// ═══════════════════════════════════════════════════════════════

export const MOCK_RECIPES = [
    {
        id: 1,
        name: 'Massa Napoletana Clássica',
        description: 'Receita tradicional de Nápoles com fermentação longa de 24-72 horas',
        category: 'Massas',
        prepTime: '30 min',
        cookTime: '90 seg',
        servings: 6,
        difficulty: 'Médio',
        image: null,
        ingredients: [
            { id: 1, name: 'Farinha Tipo 00', quantity: 1000, unit: 'g' },
            { id: 2, name: 'Água', quantity: 650, unit: 'ml' },
            { id: 3, name: 'Sal', quantity: 30, unit: 'g' },
            { id: 4, name: 'Fermento', quantity: 3, unit: 'g' }
        ],
        instructions: [
            'Dissolva o fermento na água em temperatura ambiente',
            'Adicione 70% da farinha e misture bem',
            'Incorpore o sal e o restante da farinha',
            'Sove por 15-20 minutos até a massa ficar lisa',
            'Deixe fermentar por 24-72 horas na geladeira',
            'Divida em bolinhas de 250g e deixe descansar 4h'
        ],
        notes: 'A hidratação de 65% é ideal para forno a lenha. Ajuste para 60% se usar forno convencional.',
        createdAt: '2025-11-01T10:00:00Z',
        updatedAt: '2025-12-28T14:00:00Z'
    },
    {
        id: 2,
        name: 'Molho de Tomate Artesanal',
        description: 'Molho simples que deixa o tomate San Marzano brilhar',
        category: 'Molhos',
        prepTime: '10 min',
        cookTime: '20 min',
        servings: 10,
        difficulty: 'Fácil',
        image: null,
        ingredients: [
            { id: 1, name: 'Tomate San Marzano', quantity: 800, unit: 'g' },
            { id: 2, name: 'Azeite Extra Virgem', quantity: 30, unit: 'ml' },
            { id: 3, name: 'Alho', quantity: 3, unit: 'un' },
            { id: 4, name: 'Manjericão', quantity: 10, unit: 'folhas' },
            { id: 5, name: 'Sal', quantity: 5, unit: 'g' }
        ],
        instructions: [
            'Esmague os tomates com as mãos',
            'Aqueça o azeite e doure o alho levemente',
            'Adicione os tomates e cozinhe por 15-20 min',
            'Finalize com manjericão fresco e sal a gosto'
        ],
        notes: 'Não cozinhe demais para manter o frescor do tomate.',
        createdAt: '2025-11-05T09:00:00Z',
        updatedAt: '2025-12-25T11:00:00Z'
    },
    {
        id: 3,
        name: 'Pesto Genovese',
        description: 'Receita tradicional de Gênova com manjericão fresco',
        category: 'Molhos',
        prepTime: '15 min',
        cookTime: '0 min',
        servings: 8,
        difficulty: 'Fácil',
        image: null,
        ingredients: [
            { id: 1, name: 'Manjericão Fresco', quantity: 100, unit: 'g' },
            { id: 2, name: 'Parmesão Reggiano', quantity: 50, unit: 'g' },
            { id: 3, name: 'Pinoli', quantity: 30, unit: 'g' },
            { id: 4, name: 'Alho', quantity: 2, unit: 'un' },
            { id: 5, name: 'Azeite Extra Virgem', quantity: 100, unit: 'ml' },
            { id: 6, name: 'Sal', quantity: 3, unit: 'g' }
        ],
        instructions: [
            'Lave e seque bem o manjericão',
            'Processe pinoli, alho e sal grosseiramente',
            'Adicione o manjericão e pulse',
            'Incorpore os queijos',
            'Adicione o azeite em fio com o processador ligado'
        ],
        notes: 'Use pilão para textura mais autêntica.',
        createdAt: '2025-11-10T14:00:00Z',
        updatedAt: '2025-12-20T16:00:00Z'
    },
    {
        id: 4,
        name: 'Massa de Pizza Pan',
        description: 'Massa fofa e crocante estilo Detroit/Chicago',
        category: 'Massas',
        prepTime: '20 min',
        cookTime: '15 min',
        servings: 4,
        difficulty: 'Médio',
        image: null,
        ingredients: [
            { id: 1, name: 'Farinha de Trigo', quantity: 500, unit: 'g' },
            { id: 2, name: 'Água Morna', quantity: 350, unit: 'ml' },
            { id: 3, name: 'Azeite', quantity: 30, unit: 'ml' },
            { id: 4, name: 'Açúcar', quantity: 10, unit: 'g' },
            { id: 5, name: 'Sal', quantity: 10, unit: 'g' },
            { id: 6, name: 'Fermento Seco', quantity: 7, unit: 'g' }
        ],
        instructions: [
            'Ative o fermento na água morna com açúcar',
            'Misture farinha e sal',
            'Combine líquidos e secos, adicione azeite',
            'Sove até ficar elástica',
            'Fermente 2h ou até dobrar',
            'Transfira para forma untada, deixe crescer 1h'
        ],
        notes: 'A forma de Detroit dá bordas caramelizadas perfeitas.',
        createdAt: '2025-11-15T11:00:00Z',
        updatedAt: '2025-12-22T13:00:00Z'
    },
    {
        id: 5,
        name: 'Creme de Gorgonzola',
        description: 'Molho cremoso para pizzas e bruschettas',
        category: 'Molhos',
        prepTime: '10 min',
        cookTime: '10 min',
        servings: 6,
        difficulty: 'Fácil',
        image: null,
        ingredients: [
            { id: 1, name: 'Gorgonzola', quantity: 200, unit: 'g' },
            { id: 2, name: 'Creme de Leite', quantity: 200, unit: 'ml' },
            { id: 3, name: 'Parmesão', quantity: 30, unit: 'g' },
            { id: 4, name: 'Pimenta Preta', quantity: 2, unit: 'g' }
        ],
        instructions: [
            'Aqueça o creme de leite em fogo baixo',
            'Adicione o gorgonzola picado e mexa até derreter',
            'Incorpore o parmesão ralado',
            'Tempere com pimenta a gosto'
        ],
        notes: 'Não deixe ferver para evitar separação.',
        createdAt: '2025-11-20T15:00:00Z',
        updatedAt: '2025-12-18T10:00:00Z'
    },
    {
        id: 6,
        name: 'Massa Integral',
        description: 'Opção mais saudável com farinha integral',
        category: 'Massas',
        prepTime: '25 min',
        cookTime: '12 min',
        servings: 4,
        difficulty: 'Médio',
        image: null,
        ingredients: [
            { id: 1, name: 'Farinha Integral', quantity: 300, unit: 'g' },
            { id: 2, name: 'Farinha Branca', quantity: 200, unit: 'g' },
            { id: 3, name: 'Água Morna', quantity: 325, unit: 'ml' },
            { id: 4, name: 'Mel', quantity: 15, unit: 'g' },
            { id: 5, name: 'Sal', quantity: 10, unit: 'g' },
            { id: 6, name: 'Fermento Seco', quantity: 5, unit: 'g' },
            { id: 7, name: 'Azeite', quantity: 20, unit: 'ml' }
        ],
        instructions: [
            'Misture farinhas e sal',
            'Dissolva fermento e mel na água morna',
            'Combine e sove por 10 minutos',
            'Adicione azeite e sove mais 5 minutos',
            'Fermente 2-3 horas',
            'Divida e deixe descansar 30 minutos'
        ],
        notes: 'A farinha integral absorve mais água, ajuste conforme necessário.',
        createdAt: '2025-11-25T12:00:00Z',
        updatedAt: '2025-12-15T14:00:00Z'
    }
]

// ═══════════════════════════════════════════════════════════════
// COSTS / EXPENSES MOCK DATA
// ═══════════════════════════════════════════════════════════════

export const MOCK_COSTS = [
    {
        id: 1,
        description: 'Farinha Tipo 00 - 100kg',
        category: 'Ingredientes',
        amount: 3.596,
        quantity: 100,
        type: 'Variable',
        date: '2025-12-28',
        supplier: 'Moinho Globo',
        notes: 'Pedido mensal',
        recurring: true,
        frequency: 'monthly'
    },
    {
        id: 2,
        description: 'Mussarela di Bufala',
        category: 'Ingredientes',
        amount: 125.00,
        quantity: 8,
        type: 'Variable',
        date: '2025-12-30',
        supplier: 'Laticínios Premium',
        notes: 'Entrega semanal',
        recurring: true,
        frequency: 'weekly'
    },
    {
        id: 3,
        description: 'Aluguel',
        category: 'Fixos',
        amount: 4500.00,
        quantity: 1,
        type: 'Fixed',
        date: '2025-12-01',
        supplier: '',
        notes: 'Espaço comercial 80m²',
        recurring: true,
        frequency: 'monthly'
    },
    {
        id: 4,
        description: 'Conta de Gás',
        category: 'Utilidades',
        amount: 890.00,
        quantity: 1,
        type: 'Variable',
        date: '2025-12-15',
        supplier: 'ATCO Gas',
        notes: 'Forno a gás industrial',
        recurring: true,
        frequency: 'monthly'
    },
    {
        id: 5,
        description: 'Conta de Luz',
        category: 'Utilidades',
        amount: 456.78,
        quantity: 1,
        type: 'Variable',
        date: '2025-12-15',
        supplier: 'Enmax',
        notes: '',
        recurring: true,
        frequency: 'monthly'
    },
    {
        id: 6,
        description: 'Molho San Marzano',
        category: 'Ingredientes',
        amount: 17.00,
        quantity: 30,
        type: 'Variable',
        date: '2025-12-27',
        supplier: 'Importadora Italia',
        notes: 'DOP certificado',
        recurring: false
    },
    {
        id: 7,
        description: 'Manutenção Forno',
        category: 'Manutenção',
        amount: 350.00,
        quantity: 1,
        type: 'Fixed',
        date: '2025-12-20',
        supplier: 'TechForno Services',
        notes: 'Limpeza e calibração trimestral',
        recurring: true,
        frequency: 'quarterly'
    },
    {
        id: 8,
        description: 'Salários - Dezembro',
        category: 'Pessoal',
        amount: 4250.00,
        quantity: 2,
        type: 'Fixed',
        date: '2025-12-31',
        supplier: '',
        notes: '2 funcionários tempo integral',
        recurring: true,
        frequency: 'monthly'
    },
    {
        id: 9,
        description: 'Marketing Digital',
        category: 'Marketing',
        amount: 800.00,
        quantity: 1,
        type: 'Fixed',
        date: '2025-12-01',
        supplier: 'SocialBoost Agency',
        notes: 'Instagram e Google Ads',
        recurring: true,
        frequency: 'monthly'
    },
    {
        id: 10,
        description: 'Embalagens Delivery',
        category: 'Embalagens',
        amount: 0.90,
        quantity: 500,
        type: 'Variable',
        date: '2025-12-10',
        supplier: 'EcoPack',
        notes: '500 caixas kraft',
        recurring: false
    },
    {
        id: 11,
        description: 'Seguro Empresarial',
        category: 'Fixos',
        amount: 280.00,
        quantity: 1,
        type: 'Fixed',
        date: '2025-12-01',
        supplier: 'InsureCo',
        notes: 'Cobertura completa',
        recurring: true,
        frequency: 'monthly'
    },
    {
        id: 12,
        description: 'Internet Fibra',
        category: 'Utilidades',
        amount: 120.00,
        quantity: 1,
        type: 'Fixed',
        date: '2025-12-05',
        supplier: 'Shaw',
        notes: '300mbps business',
        recurring: true,
        frequency: 'monthly'
    }
]
